" Generated by Color Theme Generator at Sweyla
" http://themes.sweyla.com/seed/748048/

set background=dark

hi clear

if exists("syntax_on")
  syntax reset
endif

" Set environment to 256 colours
set t_Co=256

let colors_name = "sweyla748048"

if version >= 700
  hi CursorLine     guibg=#030400 ctermbg=16
  hi CursorColumn   guibg=#030400 ctermbg=16
  hi MatchParen     guifg=#00AE93 guibg=#030400 gui=bold ctermfg=36 ctermbg=16 cterm=bold
  hi Pmenu          guifg=#FFFFFF guibg=#323232 ctermfg=255 ctermbg=236
  hi PmenuSel       guifg=#FFFFFF guibg=#44789D ctermfg=255 ctermbg=67
endif

" Background and menu colors
hi Cursor           guifg=NONE guibg=#FFFFFF ctermbg=255 gui=none
hi Normal           guifg=#FFFFFF guibg=#030400 gui=none ctermfg=255 ctermbg=16 cterm=none
hi NonText          guifg=#FFFFFF guibg=#12130F gui=none ctermfg=255 ctermbg=233 cterm=none
hi LineNr           guifg=#FFFFFF guibg=#1C1D19 gui=none ctermfg=255 ctermbg=234 cterm=none
hi StatusLine       guifg=#FFFFFF guibg=#101B1F gui=italic ctermfg=255 ctermbg=234 cterm=italic
hi StatusLineNC     guifg=#FFFFFF guibg=#2B2C28 gui=none ctermfg=255 ctermbg=235 cterm=none
hi VertSplit        guifg=#FFFFFF guibg=#1C1D19 gui=none ctermfg=255 ctermbg=234 cterm=none
hi Folded           guifg=#FFFFFF guibg=#030400 gui=none ctermfg=255 ctermbg=16 cterm=none
hi Title            guifg=#44789D guibg=NONE	gui=bold ctermfg=67 ctermbg=NONE cterm=bold
hi Visual           guifg=#149EE7 guibg=#323232 gui=none ctermfg=38 ctermbg=236 cterm=none
hi SpecialKey       guifg=#19D7FF guibg=#12130F gui=none ctermfg=45 ctermbg=233 cterm=none
"hi DiffChange       guibg=#4E4F00 gui=none ctermbg=58 cterm=none
"hi DiffAdd          guibg=#27284C gui=none ctermbg=235 cterm=none
"hi DiffText         guibg=#673466 gui=none ctermbg=241 cterm=none
"hi DiffDelete       guibg=#420300 gui=none ctermbg=52 cterm=none
 
hi DiffChange       guibg=#4C4C09 gui=none ctermbg=234 cterm=none
hi DiffAdd          guibg=#252556 gui=none ctermbg=17 cterm=none
hi DiffText         guibg=#66326E gui=none ctermbg=22 cterm=none
hi DiffDelete       guibg=#3F000A gui=none ctermbg=0 ctermfg=196 cterm=none
hi TabLineFill      guibg=#5E5E5E gui=none ctermbg=235 ctermfg=228 cterm=none
hi TabLineSel       guifg=#FFFFD7 gui=bold ctermfg=230 cterm=bold


" Syntax highlighting
hi Comment guifg=#44789D gui=none ctermfg=67 cterm=none
hi Constant guifg=#19D7FF gui=none ctermfg=45 cterm=none
hi Number guifg=#19D7FF gui=none ctermfg=45 cterm=none
hi Identifier guifg=#A4FFFF gui=none ctermfg=159 cterm=none
hi Statement guifg=#00AE93 gui=none ctermfg=36 cterm=none
hi Function guifg=#32FF8C gui=none ctermfg=84 cterm=none
hi Special guifg=#39F3A4 gui=none ctermfg=85 cterm=none
hi PreProc guifg=#39F3A4 gui=none ctermfg=85 cterm=none
hi Keyword guifg=#00AE93 gui=none ctermfg=36 cterm=none
hi String guifg=#149EE7 gui=none ctermfg=38 cterm=none
hi Type guifg=#00CFFF gui=none ctermfg=45 cterm=none
hi pythonBuiltin guifg=#A4FFFF gui=none ctermfg=159 cterm=none
hi TabLineFill guifg=#09415C gui=none ctermfg=23 cterm=none

